# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
apiVersion: v2
name: osmo
description: Unified OSMO control and compute plane umbrella chart
type: application
version: 0.1.0
appVersion: "6.3.1"
kubeVersion: ">=1.28.0-0"
home: https://nvidia.github.io/OSMO/main/
sources:
- https://github.com/NVIDIA/OSMO
keywords:
- osmo
- workflows
- robotics
- physical-ai
- kubernetes
icon: https://media.githubusercontent.com/media/NVIDIA/OSMO/main/docs/_static/osmo_favicon.png
dependencies:
- name: dex
  version: 0.24.1
  repository: https://charts.dexidp.io
  condition: embeddedDependencies.dex.enabled
- name: valkey
  version: 0.11.0
  repository: oci://ghcr.io/valkey-io/valkey-helm
  condition: embeddedDependencies.valkey.enabled
- name: cluster
  alias: postgresql
  version: 0.8.0
  repository: https://cloudnative-pg.github.io/charts
  condition: embeddedDependencies.postgresql.enabled
- name: rustfs
  version: "1.0.0-rc.2"
  repository: https://charts.rustfs.com
  condition: embeddedDependencies.objectStorage.enabled
