#!/bin/bash
# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

###############################################################################
# GCP Terraform driver for deploy-osmo-minimal.sh
#
# Provisions deployments/terraform/gcp/example: a dedicated VPC with Cloud NAT,
# a private zonal GKE Standard cluster reachable through its DNS control-plane
# endpoint, Cloud SQL PostgreSQL, Memorystore Redis and a GCS bucket with HMAC
# credentials. The example exposes one sensitive `deployment` output object;
# this driver turns it into the env-file contract deploy-k8s.sh consumes.
#
# Prerequisites: gcloud logged in with Application Default Credentials,
# gke-gcloud-auth-plugin, terraform >= 1.9, jq.
#
# Usage:
#   source gcp/terraform.sh
#   gcp_preflight_checks
#   gcp_terraform_apply "$TERRAFORM_DIR"
#   gcp_get_terraform_outputs "$TERRAFORM_DIR" "$OUTPUTS_FILE"
###############################################################################

GCP_SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
GCP_TERRAFORM_DIR="${GCP_TERRAFORM_DIR:-$GCP_SCRIPT_DIR/../../terraform/gcp/example}"

if [[ -z "${BLUE:-}" ]]; then
    # shellcheck disable=SC1091 # Script-relative source is resolved at runtime.
    source "$GCP_SCRIPT_DIR/../common.sh"
fi

###############################################################################
# GCP-specific Configuration Defaults
###############################################################################

TF_PROJECT_ID="${TF_PROJECT_ID:-}"
TF_CLUSTER_NAME="${TF_CLUSTER_NAME:-osmo-cluster}"
TF_GCP_REGION="${TF_GCP_REGION:-asia-southeast1}"
# Empty means "zone b of the region"; resolved by gcp_resolve_zone.
TF_GCP_ZONE="${TF_GCP_ZONE:-}"
TF_GPU_NODE_POOL_ENABLED="${TF_GPU_NODE_POOL_ENABLED:-false}"
TF_GPU_NODE_POOL_MAX_SIZE="${TF_GPU_NODE_POOL_MAX_SIZE:-2}"
TF_GPU_MACHINE_TYPE="${TF_GPU_MACHINE_TYPE:-g4-standard-48}"
TF_GPU_ACCELERATOR_TYPE="${TF_GPU_ACCELERATOR_TYPE:-nvidia-rtx-pro-6000}"

###############################################################################
# GCP Helper Functions
###############################################################################

# Private nodes with a DNS control-plane endpoint need no bastion, so the
# wrappers run plain kubectl/helm like the AWS driver. They accept both a
# single command string and separate arguments.
gcp_run_kubectl() {
    if [[ $# -eq 1 ]]; then
        eval kubectl "$1"
    else
        kubectl "$@"
    fi
}

gcp_run_kubectl_apply_stdin() {
    local manifest="$1"
    echo "$manifest" | kubectl apply -f -
}

gcp_run_helm() {
    if [[ $# -eq 1 ]]; then
        eval helm "$1"
    else
        helm "$@"
    fi
}

gcp_run_helm_with_values() {
    local values_file="$1"
    local helm_cmd="$2"
    eval helm "$helm_cmd" -f "$values_file"
}

gcp_resolve_zone() {
    TF_GCP_ZONE="${TF_GCP_ZONE:-${TF_GCP_REGION}-b}"
}

###############################################################################
# GCP Configuration Functions
###############################################################################

gcp_configure_interactively() {
    echo ""
    echo -e "${BLUE}╔══════════════════════════════════════════════════════════════════╗${NC}"
    echo -e "${BLUE}║         GCP Infrastructure - Interactive Configuration           ║${NC}"
    echo -e "${BLUE}╚══════════════════════════════════════════════════════════════════╝${NC}"
    echo ""

    local default_project="${TF_PROJECT_ID:-$(gcloud config get-value project 2>/dev/null || true)}"
    echo -e "${CYAN}Step 1: GCP Project (existing, billing enabled)${NC}"
    TF_PROJECT_ID=$(prompt_value "GCP Project ID" "$default_project")

    echo ""
    echo -e "${CYAN}Step 2: GKE Cluster Name (2-20 lowercase letters, digits, hyphens)${NC}"
    TF_CLUSTER_NAME=$(prompt_value "GKE Cluster Name" "$TF_CLUSTER_NAME")

    echo ""
    echo -e "${CYAN}Step 3: Region and Zone${NC}"
    TF_GCP_REGION=$(prompt_value "GCP Region" "$TF_GCP_REGION")
    TF_GCP_ZONE=$(prompt_value "GCP Zone" "${TF_GCP_ZONE:-${TF_GCP_REGION}-b}")

    echo ""
    log_success "Configuration complete!"
}

gcp_generate_tfvars() {
    local tfvars_file="$1"
    gcp_resolve_zone
    log_info "Generating terraform.tfvars for GCP..."

    cat > "$tfvars_file" <<EOT
# Auto-generated by deploy-osmo-minimal.sh for GCP
# Generated on: $(date)

project_id   = "$TF_PROJECT_ID"
cluster_name = "$TF_CLUSTER_NAME"
region       = "$TF_GCP_REGION"
zone         = "$TF_GCP_ZONE"

# Disposable development environment managed by --destroy: no Terraform
# deletion protection, and destroy may empty the bucket.
deletion_protection  = ${TF_GCP_DELETION_PROTECTION:-false}
bucket_force_destroy = ${TF_GCP_BUCKET_FORCE_DESTROY:-true}

# The minimal service chart trusts only public CAs for Redis TLS, while
# Memorystore issues certificates from a Google-managed private CA. Traffic
# stays unencrypted inside the private VPC instead.
redis_transit_encryption_mode = "DISABLED"

# Optional GPU pool, triggered by --gpu-node-pool. GKE installs the driver.
gpu_node_pool_enabled  = ${TF_GPU_NODE_POOL_ENABLED}
gpu_node_pool_max_size = ${TF_GPU_NODE_POOL_MAX_SIZE}
gpu_machine_type       = "${TF_GPU_MACHINE_TYPE}"
gpu_accelerator_type   = "${TF_GPU_ACCELERATOR_TYPE}"
EOT

    log_success "terraform.tfvars generated for GCP"
}

###############################################################################
# Main GCP Terraform Functions
###############################################################################

gcp_preflight_checks() {
    log_info "Running GCP pre-flight checks..."

    check_command "gcloud"
    check_command "gke-gcloud-auth-plugin"
    check_command "terraform"
    check_command "jq"

    if [[ -z "$(gcloud auth list --filter=status:ACTIVE --format='value(account)' 2>/dev/null)" ]]; then
        log_error "gcloud is not authenticated. Please run 'gcloud auth login' first."
        exit 1
    fi
    # Terraform authenticates through Application Default Credentials, which
    # are a separate credential store from the gcloud login above.
    if ! gcloud auth application-default print-access-token &>/dev/null; then
        log_error "Application Default Credentials are missing or expired."
        log_error "Run 'gcloud auth application-default login' with the same identity."
        exit 1
    fi
    if [[ -n "$TF_PROJECT_ID" ]] && ! gcloud projects describe "$TF_PROJECT_ID" --format='value(projectId)' &>/dev/null; then
        log_error "GCP project '$TF_PROJECT_ID' is not accessible with the active gcloud identity."
        exit 1
    fi

    log_success "GCP pre-flight checks passed"
}

gcp_terraform_init() {
    local terraform_dir="$1"
    log_info "Initializing Terraform for GCP..."
    cd "$terraform_dir" || return 1
    terraform init -input=false
    log_success "Terraform initialized"
}

gcp_terraform_apply() {
    local terraform_dir="$1"
    shift
    local dry_run="${1:-false}"
    if (($#)); then
        shift
    fi

    log_info "Applying Terraform configuration for GCP..."
    cd "$terraform_dir" || return 1

    if [[ "$dry_run" == true ]]; then
        log_info "[DRY-RUN] Would run: terraform plan"
        terraform plan "$@"
        return
    fi

    terraform apply -auto-approve "$@"
    log_success "Terraform apply completed"
}

gcp_terraform_destroy() {
    local terraform_dir="$1"
    local dry_run="${2:-false}"

    log_info "Destroying Terraform resources on GCP..."
    cd "$terraform_dir" || return 1

    if [[ "$dry_run" == true ]]; then
        log_info "[DRY-RUN] Would run: terraform destroy"
        return
    fi

    terraform destroy -auto-approve
    log_success "Terraform resources destroyed"
}

# Print one field of the sensitive `deployment` output.
gcp_get_terraform_output() {
    local terraform_dir="$1"
    local key="$2"
    terraform -chdir="$terraform_dir" output -json deployment | jq -r --arg key "$key" '.[$key] // empty'
}

gcp_get_terraform_outputs() {
    local terraform_dir="$1"
    local outputs_file="$2"

    log_info "Retrieving Terraform outputs from GCP..."
    local deployment
    deployment="$(terraform -chdir="$terraform_dir" output -json deployment)"

    if ! jq -e '
        ([.project_id, .cluster_name, .region, .zone, .postgres_host, .postgres_database,
          .postgres_username, .postgres_password, .redis_host, .redis_password,
          .bucket, .access_key_id, .access_key]
         | all(.[]; type == "string" and length > 0))
        and (.redis_port | type == "number" and . > 0)
    ' <<<"$deployment" >/dev/null; then
        log_error "Terraform deployment output is incomplete; re-run terraform apply"
        return 1
    fi

    # @sh single-quotes every value so passwords survive `source` unchanged.
    # Passwords stay out of the log lines below.
    {
        echo "# GCP Terraform Outputs - Auto-generated"
        echo 'export PROVIDER="gcp"'
        jq -r '
            def kv(name; value): "export \(name)=\(value | tostring | @sh)";
            kv("GCP_PROJECT_ID"; .project_id),
            kv("GCP_REGION"; .region),
            kv("GCP_ZONE"; .zone),
            kv("GKE_CLUSTER_NAME"; .cluster_name),
            kv("GKE_GPU_NODE_POOL"; (.gpu_node_pool // "")),
            kv("POSTGRES_HOST"; .postgres_host),
            kv("POSTGRES_PORT"; "5432"),
            kv("POSTGRES_DB_NAME"; .postgres_database),
            kv("POSTGRES_USERNAME"; .postgres_username),
            kv("POSTGRES_PASSWORD"; .postgres_password),
            kv("REDIS_HOST"; .redis_host),
            kv("REDIS_PORT"; .redis_port),
            kv("REDIS_PASSWORD"; .redis_password),
            kv("GCS_BUCKET"; .bucket),
            kv("GCS_ACCESS_KEY_ID"; .access_key_id),
            kv("GCS_ACCESS_KEY"; .access_key)
        ' <<<"$deployment"
        echo 'export IS_PRIVATE_CLUSTER="false"'
    } > "$outputs_file"

    # shellcheck source=/dev/null
    source "$outputs_file"

    log_success "Terraform outputs retrieved"
    log_info "  Project: $GCP_PROJECT_ID"
    log_info "  GKE Cluster: $GKE_CLUSTER_NAME ($GCP_ZONE)"
    log_info "  PostgreSQL Host: $POSTGRES_HOST"
    log_info "  Redis Host: $REDIS_HOST:$REDIS_PORT"
    log_info "  GCS Bucket: $GCS_BUCKET"
}

gcp_configure_kubectl() {
    log_info "Configuring kubectl for GKE cluster..."

    # The cluster exposes only its DNS endpoint; IAM authorizes the caller.
    gcloud container clusters get-credentials "$GKE_CLUSTER_NAME" \
        --project "$GCP_PROJECT_ID" \
        --zone "$GCP_ZONE" \
        --dns-endpoint

    kubectl get nodes
    log_success "kubectl configured successfully"
}

# Export functions (suppress output that some shells produce)
export -f gcp_run_kubectl 2>/dev/null || true
export -f gcp_run_kubectl_apply_stdin 2>/dev/null || true
export -f gcp_run_helm 2>/dev/null || true
export -f gcp_run_helm_with_values 2>/dev/null || true
export -f gcp_configure_kubectl 2>/dev/null || true
